import { Question } from "../../types";

export const NUMERICAL_QUESTIONS: Question[] = [
  // === TOPIC 1: Missing Number in the Number Series ===
  {
    id: "q_1_easy",
    topicId: "1",
    type: "interactive-sequence",
    questionText: "Find the missing number (?) that completes the logical sequence below.",
    options: ["36", "40", "42", "45"],
    correctAnswer: "2", // "42"
    explanation: "The terms are generated by the formula n² + n (starting from n = 1):\n1² + 1 = 2\n2² + 2 = 6\n3² + 3 = 12\n4² + 4 = 20\n5² + 5 = 30\n6² + 6 = 36 + 6 = 42.\nAlternatively, the differences between consecutive numbers are increasing even numbers (+4, +6, +8, +10, +12). Thus, 30 + 12 = 42.",
    difficulty: "Easy",
    hint: "Look at the differences between successive numbers: +4, +6, +8, +10. What should come next?",
    visualData: { sequence: ["2", "6", "12", "20", "30", "?"] }
  },
  {
    id: "q_1_medium",
    topicId: "1",
    type: "interactive-sequence",
    questionText: "Determine the missing term (?) that completes the sequence.",
    options: ["180", "191", "195", "201"],
    correctAnswer: "1", // "191"
    explanation: "Each term is generated by multiplying the previous term by 2 and adding 1:\n5 × 2 + 1 = 11\n11 × 2 + 1 = 23\n23 × 2 + 1 = 47\n47 × 2 + 1 = 95\n95 × 2 + 1 = 191.",
    difficulty: "Medium",
    hint: "Try doubling each number. How close is the double to the next number in the series?",
    visualData: { sequence: ["5", "11", "23", "47", "95", "?"] }
  },
  {
    id: "q_1_hard",
    topicId: "1",
    type: "interactive-sequence",
    questionText: "Analyze the cubic series logic to find the missing value (?).",
    options: ["198", "215", "217", "225"],
    correctAnswer: "2", // "217"
    explanation: "This is a cubic series matching the formula n³ + 1:\n1³ + 1 = 1 + 1 = 2\n2³ + 1 = 8 + 1 = 9\n3³ + 1 = 27 + 1 = 28\n4³ + 1 = 64 + 1 = 65\n5³ + 1 = 125 + 1 = 126\n6³ + 1 = 216 + 1 = 217.",
    difficulty: "Hard",
    hint: "Compare each number to the nearest perfect cubes: 1, 8, 27, 64, 125... What is the offset?",
    visualData: { sequence: ["2", "9", "28", "65", "126", "?"] }
  },

  // === TOPIC 3: Analogy Number ===
  {
    id: "q_3_easy",
    topicId: "3",
    type: "multiple-choice",
    questionText: "Identify the number analogy relationship:\n\n8 : 64 :: 11 : ?",
    options: ["110", "121", "132", "144"],
    correctAnswer: "1", // "121"
    explanation: "The relationship is square-based: the second term is the square of the first term. \n8² = 64.\nApplying the same rule to 11:\n11² = 121.",
    difficulty: "Easy",
    hint: "Think about the relationship between 8 and 64. It is 8 multiplied by itself.",
    visualData: { sequence: ["8", "→", "64", "::", "11", "→", "?"] }
  },
  {
    id: "q_3_medium",
    topicId: "3",
    type: "multiple-choice",
    questionText: "Solve the number analogy relationship:\n\n7 : 56 :: 9 : ?",
    options: ["81", "84", "90", "99"],
    correctAnswer: "2", // "90"
    explanation: "The relationship rule is x : x × (x + 1):\n7 : 7 × 8 = 56.\nApplying the same rule to 9:\n9 : 9 × 10 = 90.\nAlternatively, it is x : x² + x (7² + 7 = 56, and 9² + 9 = 90).",
    difficulty: "Medium",
    hint: "Try multiplying the first number by the next consecutive integer.",
    visualData: { sequence: ["7", "→", "56", "::", "9", "→", "?"] }
  },
  {
    id: "q_3_hard",
    topicId: "3",
    type: "multiple-choice",
    questionText: "Find the missing term that completes the cubic analogy:\n\n5 : 124 :: 6 : ?",
    options: ["180", "215", "216", "222"],
    correctAnswer: "1", // "215"
    explanation: "The relationship is x : x³ - 1:\n5 : 5³ - 1 = 125 - 1 = 124.\nApplying this rule to 6:\n6 : 6³ - 1 = 216 - 1 = 215.",
    difficulty: "Hard",
    hint: "Compare the second term 124 to the cube of 5. What arithmetic adjustment is made?",
    visualData: { sequence: ["5", "→", "124", "::", "6", "→", "?"] }
  },

  // === TOPIC 5: Odd one out Number / Pair of Numbers ===
  {
    id: "q_5_easy",
    topicId: "5",
    type: "multiple-choice",
    questionText: "Which number in the set is the ODD ONE OUT because it is NOT a prime number?",
    options: ["11", "13", "17", "21"],
    correctAnswer: "3", // "21"
    explanation: "11, 13, and 17 are all prime numbers (divisible only by 1 and themselves). 21 is a composite number (3 × 7 = 21). Therefore, 21 is the odd one out.",
    difficulty: "Easy",
    hint: "Look for a number that has divisors other than 1 and itself.",
    visualData: { sequence: ["11", "13", "17", "21"] }
  },
  {
    id: "q_5_medium",
    topicId: "5",
    type: "multiple-choice",
    questionText: "Which number in the set does NOT belong with the others?",
    options: ["27", "64", "125", "144"],
    correctAnswer: "3", // "144"
    explanation: "27 (3³), 64 (4³), and 125 (5³) are all perfect cubes. 144 is a perfect square (12²) but not a cube. Therefore, 144 is the odd one out.",
    difficulty: "Medium",
    hint: "Three of these numbers are perfect cubes (numbers multiplied by themselves three times). One is a square.",
    visualData: { sequence: ["27", "64", "125", "144"] }
  },
  {
    id: "q_5_hard",
    topicId: "5",
    type: "multiple-choice",
    questionText: "Identify the number pair that violates the square-mapping logic.",
    options: ["12 - 144", "13 - 169", "14 - 196", "15 - 220"],
    correctAnswer: "3", // "15 - 220"
    explanation: "All pairs represent the relationship x - x²:\n12² = 144\n13² = 169\n14² = 196\nBut 15² = 225, whereas 220 is given. Thus, '15 - 220' is the odd one out.",
    difficulty: "Hard",
    hint: "Check if the second number is the square of the first number in each pair.",
    visualData: { sequence: ["12-144", "13-169", "14-196", "15-220"] }
  },

  // === TOPIC 11: Missing Number in the Figure ===
  {
    id: "q_11_easy",
    topicId: "11",
    type: "interactive-matrix",
    questionText: "Deduce the logic of the numbers surrounding the triangle to find the missing central value (?).",
    options: ["12", "24", "36", "48"],
    correctAnswer: "1", // "24"
    explanation: "The number inside each triangle is the product of the three corner numbers divided by 2:\nTriangle 1: (3 × 4 × 2) / 2 = 24 / 2 = 12.\nTriangle 2: (4 × 5 × 3) / 2 = 60 / 2 = 30.\nTriangle 3: (3 × 8 × 2) / 2 = 48 / 2 = 24.",
    difficulty: "Easy",
    hint: "Multiply all three corner numbers, then divide by a constant factor to get the center.",
    visualData: {
      matrixGrid: [
        ["Top: 3", "", "Top: 4", "", "Top: 3"],
        ["L: 4, R: 2", "", "L: 5, R: 3", "", "L: 8, R: 2"],
        ["Center: 12", "", "Center: 30", "", "Center: ?"]
      ]
    }
  },
  {
    id: "q_11_medium",
    topicId: "11",
    type: "interactive-matrix",
    questionText: "Deconstruct the math rule of this shape: (Bottom-Left + Bottom-Right) × Top = Center. Find the missing value.",
    options: ["20", "28", "32", "45"],
    correctAnswer: "2", // "32"
    explanation: "Applying the rule (Left + Right) × Top = Center:\nFigure 1: (5 + 3) × 4 = 8 × 4 = 32.\nFigure 2: (4 + 2) × 6 = 6 × 6 = 36.\nFigure 3: (6 + 2) × 4 = 8 × 4 = 32.",
    difficulty: "Medium",
    hint: "Add the two bottom corner numbers together, then multiply by the top number.",
    visualData: {
      matrixGrid: [
        ["Top: 4", "", "Top: 6", "", "Top: 4"],
        ["L: 5, R: 3", "", "L: 4, R: 2", "", "L: 6, R: 2"],
        ["Center: 32", "", "Center: 36", "", "Center: ?"]
      ]
    }
  },
  {
    id: "q_11_hard",
    topicId: "11",
    type: "interactive-matrix",
    questionText: "Examine the quadrants in the circle below to find the missing square-based value (?).",
    options: ["36", "49", "64", "81"],
    correctAnswer: "2", // "64"
    explanation: "The values in opposite sectors are linked. The sector directly opposite a number holds its square:\n- Opposite 5 is 25 (5²)\n- Opposite 6 is 36 (6²)\n- Opposite 7 is 49 (7²)\n- Opposite 8 is ? (8² = 64).",
    difficulty: "Hard",
    hint: "Look at the numbers opposite to each other. They share a squaring relationship.",
    visualData: {
      matrixGrid: [
        ["5", "6", "7", "8"],
        ["25", "36", "49", "?"]
      ]
    }
  },

  // === TOPIC 17: Number Matrix ===
  {
    id: "q_17_easy",
    topicId: "17",
    type: "interactive-matrix",
    questionText: "Examine the rows to find the missing value in this Number Matrix.",
    options: ["14", "18", "21", "25"],
    correctAnswer: "2", // "21"
    explanation: "In each row, Column 1 + Column 2 = Column 3:\nRow 1: 5 + 10 = 15\nRow 2: 2 + 4 = 6\nRow 3: 7 + 14 = 21.",
    difficulty: "Easy",
    hint: "Look horizontally across the rows. How do the first two columns combine to produce the third?",
    visualData: {
      matrixGrid: [
        [5, 10, 15],
        [2, 4, 6],
        [7, 14, "?"]
      ]
    }
  },
  {
    id: "q_17_medium",
    topicId: "17",
    type: "interactive-matrix",
    questionText: "Deconstruct the horizontal multipliers of this row-based matrix to find the missing value.",
    options: ["48", "64", "80", "100"],
    correctAnswer: "1", // "64"
    explanation: "In each row, the numbers are generated by powers of Column 1:\nRow 1: 3, 3² (9), 3³ (27)\nRow 2: 2, 2² (4), 2³ (8)\nRow 3: 4, 4² (16), 4³ (64). Thus, the missing number is 64.",
    difficulty: "Medium",
    hint: "Look at the rows. The second column is the square of the first. What is the relationship of the third column?",
    visualData: {
      matrixGrid: [
        [3, 9, 27],
        [2, 4, 8],
        [4, 16, "?"]
      ]
    }
  },
  {
    id: "q_17_hard",
    topicId: "17",
    type: "interactive-matrix",
    questionText: "Deduce the vertical or row equation (Col1² + Col2² = Col3) to solve the matrix.",
    options: ["20", "25", "29", "35"],
    correctAnswer: "2", // "29"
    explanation: "The matrix rule is Row-based: Column 1 squared plus Column 2 squared equals Column 3.\nRow 1: 2² + 3² = 4 + 9 = 13\nRow 2: 4² + 1² = 16 + 1 = 17\nRow 3: 5² + 2² = 25 + 4 = 29.",
    difficulty: "Hard",
    hint: "Try squaring the first two numbers in each row and adding them together.",
    visualData: {
      matrixGrid: [
        [2, 3, 13],
        [4, 1, 17],
        [5, 2, "?"]
      ]
    }
  },

  // === TOPIC 19: Finding wrong in the Number Series ===
  {
    id: "q_19_easy",
    topicId: "19",
    type: "interactive-sequence",
    questionText: "Identify the WRONG number in the sequence that breaks the power of 2 progression.",
    options: ["8", "14", "32", "64"],
    correctAnswer: "1", // "14"
    explanation: "The series consists of consecutive powers of 2:\n2¹ = 2\n2² = 4\n2³ = 8\n2⁴ = 16 (but 14 is written instead of 16)\n2⁵ = 32\n2⁶ = 64. Thus, 14 is the wrong number.",
    difficulty: "Easy",
    hint: "This series is formed by doubling the previous number. Find where this rule fails.",
    visualData: { sequence: ["2", "4", "8", "14", "32", "64"] }
  },
  {
    id: "q_19_medium",
    topicId: "19",
    type: "interactive-sequence",
    questionText: "Identify the WRONG number in the sequence below that breaks the math logic.",
    options: ["9", "17", "34", "65"],
    correctAnswer: "2", // "34"
    explanation: "The pattern is: Term × 2 - 1.\n3 × 2 - 1 = 5\n5 × 2 - 1 = 9\n9 × 2 - 1 = 17\n17 × 2 - 1 = 33 (but 34 is written instead of 33)\n33 × 2 - 1 = 65. Hence, 34 is the wrong number.",
    difficulty: "Medium",
    hint: "Each step doubles the previous number and subtracts 1. Find where this rule fails.",
    visualData: { sequence: ["3", "5", "9", "17", "34", "65"] }
  },
  {
    id: "q_19_hard",
    topicId: "19",
    type: "interactive-sequence",
    questionText: "Spot the wrong cube term in this cubic-based sequence.",
    options: ["8", "27", "120", "216"],
    correctAnswer: "2", // "120"
    explanation: "The series consists of consecutive perfect cubes:\n1³ = 1\n2³ = 8\n3³ = 27\n4³ = 64\n5³ = 125 (but 120 is written instead of 125)\n6³ = 216. Hence, 120 is the wrong term.",
    difficulty: "Hard",
    hint: "Are these numbers perfect cubes? (1, 8, 27, 64, 125...)",
    visualData: { sequence: ["1", "8", "27", "64", "120", "216"] }
  },

  // === TOPIC 20: Numerical Problems ===
  {
    id: "q_20_easy",
    topicId: "20",
    type: "multiple-choice",
    questionText: "A parent is exactly 3 times as old as their child. If the sum of their ages is 40 years, how old is the child?",
    options: ["8 years", "10 years", "12 years", "15 years"],
    correctAnswer: "1", // "10 years"
    explanation: "Let the child's age be x. Then the parent's age is 3x.\nTogether: x + 3x = 40\n4x = 40\nx = 10 years. The child is 10 years old.",
    difficulty: "Easy",
    hint: "If the child's age is x, the parent's age is 3x. Sum them to equal 40 and solve for x.",
    visualData: { sequence: ["Parent = 3 × Child", "Parent + Child = 40", "Child = ?"] }
  },
  {
    id: "q_20_medium",
    topicId: "20",
    type: "multiple-choice",
    questionText: "A clock strikes 4 times at 4 o'clock, taking 6 seconds. How long does it take to strike 12 times at 12 o'clock?",
    options: ["18 seconds", "22 seconds", "24 seconds", "30 seconds"],
    correctAnswer: "1", // "22 seconds"
    explanation: "A clock striking 4 times has 3 intervals of silence between strikes. If 3 intervals take 6 seconds, each interval takes 6 / 3 = 2 seconds.\nAt 12 o'clock, the clock strikes 12 times, which contains 11 intervals. 11 intervals × 2 seconds = 22 seconds.",
    difficulty: "Medium",
    hint: "The time spent striking is determined by the silence intervals between strikes. How many intervals are in 4 strikes?",
    visualData: { sequence: ["Strike 1", "— 2s —", "Strike 2", "— 2s —", "Strike 3", "— 2s —", "Strike 4"] }
  },
  {
    id: "q_20_hard",
    topicId: "20",
    type: "multiple-choice",
    questionText: "A small snail climbs up a 10-meter high wall. Every day it climbs up 3 meters, but slips down 2 meters every night. How many days will it take for the snail to reach the top of the wall?",
    options: ["7 days", "8 days", "9 days", "10 days"],
    correctAnswer: "1", // "8 days"
    explanation: "Each day, the net progress of the snail is 3 - 2 = 1 meter.\nHowever, on the final day, once the snail reaches the top (10m), it does not slip back down.\nLet's calculate day-by-day:\n- Day 7 starts at 6m, climbs +3m to 9m, slips back to 7m.\n- Day 8 starts at 7m, climbs +3m to reach 10m (reaches the top!). It does not slip. Thus, it takes exactly 8 days.",
    difficulty: "Hard",
    hint: "On the very last day, when the snail reaches the top 10-meter mark, it does not slide down. Subtract 3m from 10m first.",
    visualData: { sequence: ["Net daily rise = 1m", "On the last day, it climbs 3m and exits", "Total height = 10m"] }
  },

  // === TOPIC 26: Ranking Test and Number / Letter Test ===
  {
    id: "q_26_easy",
    topicId: "26",
    type: "multiple-choice",
    questionText: "In a class of 40 students, Raj ranks 15th from the top. What is his position ranking from the bottom?",
    options: ["24th", "25th", "26th", "27th"],
    correctAnswer: "2", // "26th"
    explanation: "Position from Bottom = (Total Students - Rank from Top) + 1.\nRaj's rank = (40 - 15) + 1 = 25 + 1 = 26th.",
    difficulty: "Easy",
    hint: "Subtract Raj's top position from the total number of students, then add 1 to count Raj himself.",
    visualData: { sequence: ["Top [1]", "...", "Raj [15th]", "...", "Bottom [40th]"] }
  },
  {
    id: "q_26_medium",
    topicId: "26",
    type: "multiple-choice",
    questionText: "In a single-file line of students, Rohan is standing 10th from the front and 15th from the back. How many students are in the line in total?",
    options: ["23", "24", "25", "26"],
    correctAnswer: "1", // "24"
    explanation: "Total Students = (Rank from Front + Rank from Back) - 1.\nTotal = (10 + 15) - 1 = 25 - 1 = 24.\nWe subtract 1 because Rohan is counted twice (once from front and once from back).",
    difficulty: "Medium",
    hint: "Add his position from the front and back, then subtract 1 since he is counted twice.",
    visualData: { sequence: ["Front (9 students)", "→ Rohan (1) ←", "Back (14 students)"] }
  },
  {
    id: "q_26_hard",
    topicId: "26",
    type: "multiple-choice",
    questionText: "In a row of boys, A is 10th from the left and B is 9th from the right. If they interchange their positions, A becomes 15th from the left. How many boys are there in the row?",
    options: ["22", "23", "24", "25"],
    correctAnswer: "1", // "23"
    explanation: "Before interchanging, B was 9th from the right.\nAfter interchanging, A sits at B's original spot, which is 9th from the right.\nThe problem states A's new position is also 15th from the left.\nThus, this position is 15th from left and 9th from right.\nTotal boys = (15 + 9) - 1 = 24 - 1 = 23.",
    difficulty: "Hard",
    hint: "The spot A moves to was 9th from the right. Since A is now 15th from the left at that spot, use the standard ranking formula.",
    visualData: { sequence: ["Left ... [10th: A]", " ... [9th: B] ... Right", "Interchanged: Spot B is now [15th Left]"] }
  }
];
